### ISSUE TITLE
ClassCastException in Node.pluralIdentifyingRootFieldFut

### ISSUE THREAD

**Issue by stephane-debart** [sangria-graphql/sangria-relay#29]
When trying to use the Node.pluralIdentifyingRootFieldFut function, I get the following exception:

java.lang.ClassCastException: scala.collection.immutable.Vector cannot be cast to scala.collection.immutable.List
	at sangria.relay.Node$.$anonfun$pluralIdentifyingRootFieldFut$1(Node.scala:109)
	at sangria.execution.Resolver.resolveField(Resolver.scala:1007)
	at sangria.execution.Resolver.$anonfun$collectActionsPar$1(Resolver.scala:440)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)

The argName argument should thus not be casted in List :  "ctx.arg[List[T]](argName)"
When casted in Vector as in pluralIdentifyingRootField, it works correctly.

**Comment by OlegIlyenko** [comment]
Thanks a lot for the report!

**Comment by stephane-debart** [comment]
Just integrated 1.3.1. This works fine.
Thanks Oleg for this and all your work on Sangria.
